# Generated by Django 3.2.3 on 2021-10-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_documenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttype',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
