# Generated by Django 3.2.3 on 2021-10-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_alter_documenttype_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRunDocType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.UUIDField()),
                ('course_run_key', models.CharField(max_length=100)),
                ('doc_types', models.CharField(max_length=200)),
            ],
        ),
    ]
