# Generated by Django 3.2.3 on 2021-11-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_courserundoctype'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='expiry_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='validation_error',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
