# Generated by Django 3.2.3 on 2021-11-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0006_auto_20211114_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(blank=True, choices=[('n', 'Нет статуса'), ('v', 'Проверен'), ('r', 'Возвращен')], default='n', help_text='Состояние документа', max_length=1),
        ),
    ]
