# Generated by Django 3.2.3 on 2021-11-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0007_alter_document_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='expiry_date',
            field=models.DateField(null=True, verbose_name='Действителен до'),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(blank=True, choices=[('n', 'Нет статуса'), ('v', 'Проверен'), ('r', 'Возвращен')], default='n', help_text='Состояние проверки документа модератором', max_length=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='document',
            name='validation_error',
            field=models.CharField(max_length=200, null=True, verbose_name='Замечания проверки'),
        ),
    ]
