# Generated by Django 3.2.3 on 2021-11-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0008_auto_20211116_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='validation_error',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Замечания проверки'),
        ),
    ]
