# Generated by Django 3.2.3 on 2021-12-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0009_alter_document_validation_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='email',
            field=models.CharField(max_length=200, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='document',
            name='student_fio',
            field=models.CharField(max_length=200, null=True, verbose_name='Студент'),
        ),
    ]
