# Generated by Django 3.2.3 on 2021-12-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0010_auto_20211211_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('student_id', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=200, verbose_name='Тип документа')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('expiry_date', models.DateField(null=True, verbose_name='Действителен до')),
                ('validation_error', models.CharField(blank=True, max_length=200, null=True, verbose_name='Замечания проверки')),
                ('status', models.CharField(blank=True, choices=[('n', 'Нет статуса'), ('v', 'Проверен'), ('r', 'Возвращен')], default='n', help_text='Состояние проверки документа модератором', max_length=1, verbose_name='Статус')),
                ('email', models.CharField(max_length=200, null=True, verbose_name='E-mail')),
                ('student_fio', models.CharField(max_length=200, null=True, verbose_name='Студент')),
            ],
        ),
    ]
