# Generated by Django 3.2.3 on 2021-10-09 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_file_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='author',
        ),
    ]
