# Generated by Django 3.2.3 on 2021-12-18 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0011_documentarchive'),
        ('files', '0004_remove_file_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='docs.documentarchive')),
            ],
        ),
    ]
